### ISSUE TITLE
Kommunikation zwischen Server und Client

### ISSUE THREAD

**Issue by JanK411** [JanK411/yada#4]
via Json sollten irgendwie tolle Kommandos an den Server weitergegeben werden können... Dafür brauchen wir vielleicht eine Kommando-Struktur, die permanent konsistent ist zwischen **app** (JS) und **model** (Java)

**Comment by JanK411** [comment]
Kommandostruktur ist vermutlich fertig, Server und App können jedoch noch nicht miteinander reden
Es muss nun herausgefunden werden, wie ein RPC-Call aus js heraus fliegen kann

**Comment by Uschi003** [comment]
https://stackoverflow.com/questions/3033755/reading-post-data-from-html-form-sent-to-serversocket

lululu - ich lass den mal hier fallen ~ wenn das läuft, dann sollte die kommunikation von client zu server laufen. Die  Rückrichtung bleibt aber noch offen, weil der Server ja auch, je nach Command, einen anderen Client anpingt (:

**Comment by JanK411** [comment]
steht, allerdings kommen noch keine responses an, wie mir scheint...

**Comment by JanK411** [comment]
@Uschi003 sowohl in der server.java als auch in der setup.ts steht je ein FIXME für dich <3

**Comment by JanK411** [comment]
ich finde Jeremy hat das richtig toll gemacht, ich schließ das issue jetzt <3
